services:

  db:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    # environment:
        # MONGO_INITDB_DATABASE: scouting-field
        # MONGO_INITDB_ROOT_USERNAME: admin
        # MONGO_INITDB_ROOT_PASSWORD: pass
    env_file:
      - .env
    volumes:
      - .data/mongo:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 40s
    # networks:
    #   - backend

  backend:
    # image: '${DOCKER_IMAGE_BACKEND?Variable not set}:${TAG-latest}'
    build: ./backend
    restart: always
    ports:
      - "8000:8000"
    environment:
      MONGO_HOST: db
    depends_on:
      db:
        condition: service_healthy
        restart: true
  #   networks:
  #     - backend

# networks:
#   backend:
#     driver: bridge